SELECT PROD.PRODUCT_NAME, SUM(ORDT.ORDER_ITEM_SUBTOTAL) FROM ORDERS ORD 
INNER JOIN ORDER_ITEMS ORDT ON ORD.ORDER_ID=ORDT.ORDER_ITEM_ORDER_ID
INNER JOIN PRODUCTS PROD ON ORDT.ORDER_ITEM_PRODUCT_ID=PROD.PRODUCT_ID
WHERE ORD.ORDER_STATUS IN ('CLOSED','COMPLETED') AND ORD.ORDER_DATE='2014-07-24'
GROUP BY PROD.PRODUCT_NAME ORDER BY 2 DESC; 

-- SELECT COUNT(DISTINCT ORDER_DATE) FROM ORDERS;

SELECT * FROM ORDER_ITEMS LIMIT 10;
-- ORDER_ITEM_PRODUCT_ID

SELECT * FROM PRODUCTS LIMIT 10;

SELECT to_char(ORDER_DATE,'yyyy-MM') AS ORDER_MONTH, COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY 1
ORDER BY 2 DESC;

SELECT ORDER_ITEM_ORDER_ID, ROUND(SUM(ORDER_ITEM_PRODUCT_PRICE)::numeric) AS TOTAL_REVENUE
FROM ORDER_ITEMS
GROUP BY 1
ORDER BY 2 DESC;